import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import BalanceContract from "../components/BalanceContract";
import { contractAddresses } from "../constants/contractAddresses.json";
import { abi } from "../constants/abi.json";
import { Button } from "web3uikit";
import { useMoralis, useWeb3Contract } from "react-moralis";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <BalanceContract />
      <main className={styles.main}></main>
    </>
  );
}
